title: My totally awesome title
author: FreyGeospatial
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site will be useful for learning about GitHub Pages. I can edit this
  line in _config.yml. This will appear in the document head meta (for
  Google search results) and in the feed.xml site description.
theme: minima

# social links
twitter_username: freygeospatial # DO NOT include the @ character, or else the build will fail!
github_username:  freygeospatial # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
